#!/bin/bash

echo "Setting up git global identity..."
echo ""

echo -n "Full name: "
read -r FULLNAME

echo -n "Email address: "
read -r EMAIL

git config --global user.name "${FULLNAME}"
git config --global user.email "${EMAIL}"
git config --global credential.helper 'cache --timeout=86400'

echo "Git reports the following changes:"
echo "  user.name: $(git config --global user.name)"
echo "  user.email: $(git config --global user.email)"

