#!/bin/bash

# Open up the docker socket so that our container can talk to it
sudo chmod 777 /var/run/docker.sock

DEVICE=""
[ -c /dev/i2c-1 ] && DEVICE="--device /dev/i2c-1 --device /dev/i2c-3"
CLOCK=""
[ -f /var/lib/systemd/clock ] && CLOCK="-v /var/lib/systemd/clock:/var/lib/systemd/clock:rw"

docker run -d --restart="always" --name node-dev-container-2 --hostname dev --net="host" ${DEVICE} ${VOLUMES} -v node-dev-home:/home/dev:rw -v /var/run/docker.sock:/var/run/docker.sock:rw -v /run/systemd:/run/systemd:rw -v /var/run/libvirt/libvirt-sock:/var/run/libvirt/libvirt-sock:rw ${CLOCK} toddbu/node-dev-container:2.0.0
